import { useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { useOrg } from '../api'

export function CompanySetup() {
  const org = useOrg(); const cache = useQueryClient(); const [message, setMessage] = useState('')
  const [company, setCompany] = useState('Nexgile Industries'); const [entity, setEntity] = useState('Nexgile India'); const [country, setCountry] = useState('IN')
  const create = async () => { const res = await fetch('/api/v1/org', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ company_name: company, entity_name: entity, country }) }); const body = await res.json(); if (!res.ok) throw new Error(body.detail); await cache.invalidateQueries(); setMessage(`Company created. Entity ID ${body.entity_id}`) }
  const add = async (name: string, city: string, type: string) => { const entityId = org.data?.entities[0]?.id; if (!entityId) throw new Error('Create the company first'); const res = await fetch('/api/v1/org/facilities', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ entity_id: entityId, name, city, country, facility_type: type }) }); const body = await res.json(); if (!res.ok) throw new Error(body.detail); await cache.invalidateQueries(); setMessage(`${name} created`) }
  return <div className="max-w-2xl space-y-5"><div><p className="text-xs font-medium text-sky-800">Step 1</p><h1 className="mt-1 text-2xl font-semibold">Company and facilities</h1><p className="mt-1 text-sm text-slate-500">Set up operational locations before factory managers report monthly activity data.</p></div>{org.data ? <section className="border border-slate-200 bg-white p-5"><h2 className="font-semibold">{org.data.name}</h2><div className="mt-4 flex flex-wrap gap-2">{org.data.entities.flatMap((e) => e.facilities).map((f) => <span key={f.id} className="rounded bg-slate-100 px-3 py-1 text-sm">{f.name}</span>)}</div><div className="mt-5 flex flex-wrap gap-2">{[['Hyderabad Plant','Hyderabad','manufacturing'],['Pune Plant','Pune','manufacturing'],['Chennai Warehouse','Chennai','warehouse']].map(([name, city, type]) => <button key={name} onClick={() => add(name, city, type)} className="rounded border border-sky-300 px-3 py-2 text-sm text-sky-800">Add {name}</button>)}</div></section> : <section className="space-y-3 border border-slate-200 bg-white p-5"><label className="grid gap-1 text-sm">Company<input value={company} onChange={(e) => setCompany(e.target.value)} className="rounded border p-2" /></label><label className="grid gap-1 text-sm">Entity<input value={entity} onChange={(e) => setEntity(e.target.value)} className="rounded border p-2" /></label><label className="grid gap-1 text-sm">Country<input value={country} onChange={(e) => setCountry(e.target.value.toUpperCase())} className="rounded border p-2" /></label><button onClick={() => create().catch((e) => setMessage(e.message))} className="rounded bg-sky-800 px-4 py-2 text-sm text-white">Create company</button></section>}{message && <p className="rounded bg-slate-100 p-3 text-sm">{message}</p>}</div>
}
