import { useState } from 'react'

import { fmt, titleCase, useProductAlternatives, useProductBom, useProductPcf, useProducts } from '../api'

export function Products() {
  const products = useProducts()
  const [chosenId, setChosenId] = useState<number | null>(null)
  const productId = chosenId ?? products.data?.[0]?.id ?? null
  const bom = useProductBom(productId)
  const pcf = useProductPcf(productId)
  const alternatives = useProductAlternatives(productId)

  return <div className="space-y-5">
    <div><p className="text-xs font-medium text-sky-800">Product carbon footprint</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Design carbon into product decisions</h1><p className="mt-1 text-sm text-slate-500">BOM-level factor calculations are separated from approved corporate inventory actuals.</p></div>
    <div className="grid gap-3 md:grid-cols-2">{(products.data ?? []).map((product) => <button key={product.id} onClick={() => setChosenId(product.id)} className={`border p-4 text-left shadow-sm transition active:translate-y-px ${product.id === productId ? 'border-sky-400 bg-sky-50' : 'border-slate-200 bg-white hover:border-slate-300'}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">{product.name}</p><p className="mt-1 text-xs text-slate-500">{product.sku} · {product.boundary.replace(/_/g, ' ')}</p></div><span className="num text-sm font-semibold text-sky-900">{fmt(product.pcf_kgco2e, 2)} kg</span></div></button>)}</div>
    {pcf.data && <div className="grid gap-5 xl:grid-cols-5"><section className="border border-slate-200 bg-white p-5 shadow-sm xl:col-span-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold">{pcf.data.product.name} footprint</h2><p className="mt-1 text-xs text-slate-500">{pcf.data.product.functional_unit} · {pcf.data.product.boundary.replace(/_/g, ' ')}</p></div><div className="text-right"><p className="num text-2xl font-semibold">{fmt(pcf.data.total_kgco2e, 2)} kgCO₂e</p><p className="mt-1 text-xs text-amber-800">{pcf.data.verification_status.replace(/_/g, ' ')} · ±{fmt(pcf.data.uncertainty_pct, 0)}%</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{pcf.data.stages.map((stage) => <div key={stage.stage} className="border-l-2 border-sky-600 bg-slate-50 px-3 py-2"><p className="text-xs font-medium text-slate-600">{titleCase(stage.stage)}</p><p className="num mt-1 text-lg font-semibold">{fmt(stage.kgco2e, 2)} kgCO₂e</p><p className="mt-1 text-xs text-slate-500">{stage.method}</p></div>)}</div></section><section className="border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><h2 className="text-sm font-semibold">Method notes</h2><ul className="mt-3 space-y-3 text-sm leading-relaxed text-slate-600">{pcf.data.assumptions.map((note) => <li key={note}>{note}</li>)}</ul></section></div>}
    <div className="grid gap-5 xl:grid-cols-5"><section className="overflow-hidden border border-slate-200 bg-white shadow-sm xl:col-span-3"><div className="border-b border-slate-200 p-4"><h2 className="text-sm font-semibold">Bill of materials</h2><p className="mt-1 text-xs text-slate-500">Each material result uses the versioned factor shown in its row.</p></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-medium text-slate-500"><tr><th className="px-4 py-3">Component</th><th className="px-4 py-3">Material</th><th className="px-4 py-3 text-right">Mass</th><th className="px-4 py-3">Factor</th><th className="px-4 py-3 text-right">Result</th></tr></thead><tbody className="divide-y divide-slate-100">{(bom.data?.rows ?? []).map((item) => <tr key={item.id}><td className="px-4 py-3 font-medium" style={{ paddingLeft: `${16 + (item.parent_bom_item_id ? 18 : 0)}px` }}>{item.component_name}</td><td className="px-4 py-3 text-slate-600">{item.material}</td><td className="num px-4 py-3 text-right">{fmt(item.mass_kg * item.quantity, 3)} kg</td><td className="px-4 py-3 text-xs text-slate-600">{item.factor ? `${item.factor.code} ${item.factor.version}` : 'No factor'}</td><td className="num px-4 py-3 text-right font-medium">{fmt(item.kgco2e, 3)} kg</td></tr>)}</tbody></table></div></section>{alternatives.data && <section className="border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><h2 className="text-sm font-semibold">Aluminium alternative</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">{alternatives.data.note}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="border border-slate-200 p-3"><p className="text-xs text-slate-500">Virgin</p><p className="num mt-1 text-lg font-semibold">{fmt(alternatives.data.current_kgco2e, 2)} kg</p><p className="mt-1 text-xs text-slate-500">{alternatives.data.current_factor.code}</p></div><div className="border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs text-emerald-800">Recycled</p><p className="num mt-1 text-lg font-semibold text-emerald-900">{fmt(alternatives.data.alternative_kgco2e, 2)} kg</p><p className="mt-1 text-xs text-emerald-800">{alternatives.data.alternative_factor.code}</p></div></div><p className="num mt-4 text-sm font-semibold text-emerald-800">{fmt(-alternatives.data.delta_kgco2e, 2)} kgCO₂e avoided ({fmt(alternatives.data.reduction_pct)}%)</p></section>}</div>
  </div>
}
