import { useState } from 'react'

import { fmt, titleCase, useScenario } from '../api'

type Lever = 'renewable_electricity_pct' | 'recycled_material_pct' | 'freight_mode_shift_pct' | 'supplier_switch_pct'
const LABELS: Record<Lever, string> = { renewable_electricity_pct: 'Renewable electricity', recycled_material_pct: 'Recycled material', freight_mode_shift_pct: 'Freight mode shift', supplier_switch_pct: 'Supplier switch' }

export function Scenarios() {
  const [values, setValues] = useState<Record<Lever, number>>({ renewable_electricity_pct: 50, recycled_material_pct: 25, freight_mode_shift_pct: 20, supplier_switch_pct: 15 })
  const model = useScenario()
  return <div className="max-w-5xl space-y-5"><div><p className="text-xs font-medium text-sky-800">Abatement planning</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Model a reduction pathway</h1><p className="mt-1 text-sm text-slate-500">Test business levers against the current inventory without changing any approved calculation.</p></div><section className="border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-900">Scenario output only. Approved corporate actuals remain unchanged.</section><div className="grid gap-5 lg:grid-cols-2"><section className="border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold">Lever assumptions</h2><div className="mt-5 space-y-5">{(Object.keys(values) as Lever[]).map((key) => <label key={key} className="block"><div className="flex justify-between gap-4 text-sm"><span className="font-medium">{LABELS[key]}</span><span className="num text-slate-600">{values[key]}%</span></div><input className="mt-2 w-full accent-sky-700" type="range" min="0" max="100" value={values[key]} onChange={(event) => setValues({ ...values, [key]: Number(event.target.value) })} /></label>)}</div><button onClick={() => model.mutate(values)} disabled={model.isPending} className="mt-6 rounded bg-sky-800 px-4 py-2 text-sm font-medium text-white transition active:translate-y-px disabled:opacity-50">{model.isPending ? 'Modelling…' : 'Model scenario'}</button></section><ScenarioResult result={model.data} error={model.error as Error | null} /></div></div>
}

function ScenarioResult({ result, error }: { result?: ReturnType<typeof useScenario>['data']; error: Error | null }) {
  if (error) return <section className="border border-red-200 bg-red-50 p-5 text-sm text-red-800">Scenario could not be modelled: {error.message}</section>
  if (!result) return <section className="border border-slate-200 bg-white p-5 text-sm text-slate-500 shadow-sm">Select assumptions and run the model to compare the current inventory with a potential pathway.</section>
  return <section className="border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold">Modelled outcome</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="border border-slate-200 p-3"><p className="text-xs text-slate-500">Current</p><p className="num mt-1 text-xl font-semibold">{fmt(result.baseline_tco2e)} tCO₂e</p></div><div className="border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs text-emerald-800">Scenario</p><p className="num mt-1 text-xl font-semibold text-emerald-900">{fmt(result.result_tco2e)} tCO₂e</p></div></div><p className="num mt-4 text-sm font-semibold text-emerald-800">{fmt(result.avoided_tco2e)} tCO₂e avoided ({fmt(result.reduction_pct)}%)</p><div className="mt-5 space-y-2">{result.reductions.map((item) => <div key={item.lever} className="flex justify-between border-b border-slate-100 pb-2 text-sm"><span>{titleCase(item.lever)}</span><span className="num font-medium">{fmt(item.tco2e)} tCO₂e</span></div>)}</div><p className="mt-5 text-xs text-slate-500">Screening range: P5 {fmt(result.range.p5_tco2e)} · P50 {fmt(result.range.p50_tco2e)} · P95 {fmt(result.range.p95_tco2e)} tCO₂e</p></section>
}
